openapi: 3.0.3
info:
  title: Finance Manager API
  version: 0.0.1
  description: The backend API for the Finance Manager application.
paths:
  /balance/:
    post:
      operationId: balance_create
      tags:
      - balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/compconents/schemas/Balance'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Balance'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Balance'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
          description: ''
  /balance/{id}/:
    get:
      operationId: balance_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - balance
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
          description: ''
    put:
      operationId: balance_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Balance'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Balance'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Balance'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
          description: ''
    patch:
      operationId: balance_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBalance'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBalance'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBalance'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
          description: ''
    delete:
      operationId: balance_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - balance
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /transactions/:
    get:
      operationId: transactions_list
      tags:
      - transactions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
          description: ''
    post:
      operationId: transactions_create
      tags:
      - transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
  /transactions/{id}/:
    get:
      operationId: transactions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - transactions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
    put:
      operationId: transactions_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
    patch:
      operationId: transactions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTransaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTransaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTransaction'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
    delete:
      operationId: transactions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - transactions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Balance:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,18}(?:\.\d{0,2})?$
        currency:
          $ref: '#/components/schemas/CurrencyEnum'
        user:
          type: integer
      required:
      - amount
      - currency
      - id
      - user
    CurrencyEnum:
      enum:
      - EUR
      - USD
      - UAH
      - BTC
      type: string
      description: |-
        * `EUR` - Euro
        * `USD` - US Dollar
        * `UAH` - Ukrainian hryvnia
        * `BTC` - Bitcoin
    PatchedBalance:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,18}(?:\.\d{0,2})?$
        currency:
          $ref: '#/components/schemas/CurrencyEnum'
        user:
          type: integer
    PatchedTransaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        date:
          type: string
          format: date
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,18}(?:\.\d{0,2})?$
        currency:
          $ref: '#/components/schemas/CurrencyEnum'
        user:
          type: integer
    Transaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        date:
          type: string
          format: date
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,18}(?:\.\d{0,2})?$
        currency:
          $ref: '#/components/schemas/CurrencyEnum'
        user:
          type: integer
      required:
      - amount
      - currency
      - date
      - id
      - user
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
