# Generated by Django 5.2.7 on 2025-12-14 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_balance_amount_alter_currency_rate_and_more'),
        ('monobank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monobankuser',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MonobankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monobank_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('watch', models.BooleanField(default=False)),
                ('balance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.balance')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
