# Generated by Django 5.2.7 on 2025-12-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('monobank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonobankBalance',
            fields=[
                ('balance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.balance')),
                ('monobank_id', models.CharField(max_length=100)),
                ('watch', models.BooleanField(default=False)),
            ],
            bases=('finances.balance',),
        ),
    ]
