# Generated by Django 5.2.7 on 2025-12-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_balance_amount_alter_currency_rate_and_more'),
        ('monobank', '0002_alter_monobankuser_last_synced_at_monobankbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monobankbalance',
            name='balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.balance'),
        ),
        migrations.AlterField(
            model_name='monobankbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monobank.monobankuser'),
        ),
    ]
