# Generated by Django 5.2.7 on 2025-12-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_balance_amount_alter_currency_rate_and_more'),
        ('monobank', '0003_alter_monobankbalance_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonobankTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.transaction')),
                ('monobank_id', models.CharField(max_length=100)),
            ],
            bases=('finances.transaction',),
        ),
    ]
