# Generated by Django 5.2.7 on 2025-12-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_balance_amount_alter_currency_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='id',
            new_name='id_val',
        ),
    ]
