# Generated by Django 5.2.7 on 2025-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('alpha_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('num_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
