# Generated by Django 5.2.7 on 2025-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_rename_id_currency_id_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='id_val',
            new_name='id',
        ),
    ]
